In [1]:
import pandas as pd

In [2]:
csv_path = "EOD_20181027_v1.csv"
# col_names = ["Stock", "Date","Adj Close"]

In [3]:
df = pd.read_csv(csv_path)

In [4]:
df.columns = ['adj_close','stock','date','records']

In [5]:
stock_df = df[['date','adj_close','stock']]

In [6]:
stock_df.head()

         date  adj_close stock
0  10/23/2014      65.92  ADBE
1  10/24/2014      67.01  ADBE
2  10/27/2014      67.03  ADBE
3  10/28/2014      68.37  ADBE
4  10/29/2014      67.93  ADBE

In [9]:
stock_df.dtypes

date         datetime64[ns]
adj_close           float64
stock                object
dtype: object

In [8]:
stock_df['date']=pd.to_datetime(df.date)

C:\Users\Jeff\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [11]:
pivot_df = stock_df.pivot(index='date', columns='stock', values='adj_close')

In [12]:
pivot_df = pivot_df.reset_index()

In [14]:
pivot_df.sort_values(by=['date'],inplace=True)

In [16]:
pivot_df.tail(1000)

stock,date,A,AA,AAAP,AAAU,AABA,AAC,AADR,AAIT,AAL,...,ZUMZ,ZUO,ZVZZC,ZVZZCNX,ZX,ZXYZ_A,ZYME,ZYNE,ZZK,ZZZ
13446,2014-11-07,39.340497,NaN,NaN,NaN,48.550,25.50,36.597672,33.029636,41.697657,...,35.10,NaN,NaN,NaN,1.4700,NaN,NaN,NaN,100.0,0.5
13447,2014-11-10,39.917196,NaN,NaN,NaN,49.410,26.48,36.950420,33.029636,42.305747,...,33.91,NaN,NaN,NaN,1.5300,NaN,NaN,NaN,100.0,0.5
13448,2014-11-11,40.042148,NaN,NaN,NaN,49.050,24.96,36.950420,33.029636,41.929310,...,33.94,NaN,NaN,NaN,1.5300,NaN,NaN,NaN,100.0,0.5
13449,2014-11-12,39.840303,NaN,NaN,NaN,50.600,25.00,36.783845,33.530714,41.919658,...,35.89,NaN,NaN,NaN,1.5200,NaN,NaN,NaN,100.0,0.5
13450,2014-11-13,39.840303,NaN,NaN,NaN,50.500,26.76,36.783845,33.408163,42.585662,...,35.42,NaN,NaN,NaN,1.1700,NaN,NaN,NaN,100.0,0.5
13451,2014-11-14,39.955643,NaN,NaN,NaN,51.750,26.46,36.852533,33.408163,42.479488,...,35.49,NaN,NaN,NaN,1.2100,NaN,NaN,NaN,100.0,0.5
13452,2014-11-17,39.638458,NaN,NaN,NaN,52.370,28.03,36.970017,33.408163,42.170616,...,33.98,NaN,NaN,NaN,1.2690,NaN,NaN,NaN,100.0,0.5
13453,2014-11-18,39.215546,NaN,NaN,NaN,51.750,29.35,36.970017,33.337992,43.483320,...,33.84,NaN,NaN,NaN,1.3300,NaN,NaN,NaN,100.0,0.5
13454,2014-11-19,39.215546,NaN,NaN,NaN,50.580,29.14,36.911226,33.030625,42.566358,...,33.99,NaN,NaN,NaN,1.2600,NaN,NaN,NaN,100.0,0.5
13455,2014-11-20,39.657682,NaN,NaN,NaN,51.250,27.02,36.842636,33.029636,42.624271,...,35.52,NaN,NaN,NaN,1.3301,NaN,NaN,NaN,100.0,0.5
13456,2014-11-21,40.609235,NaN,NaN,NaN,51.040,26.04,37.515406,33.029636,41.803831,...,35.69,NaN,NaN,NaN,1.2975,NaN,NaN,NaN,100.0,0.5
13457,2014-11-24,40.609235,NaN,NaN,NaN,51.830,26.60,37.263975,33.356770,41.707309,...,36.57,NaN,NaN,NaN,1.2600,NaN,NaN,NaN,100.0,0.5
13458,2014-11-25,41.051371,NaN,NaN,NaN,51.720,28.44,37.468765,33.375548,42.614619,...,36.18,NaN,NaN,NaN,1.3700,NaN,NaN,NaN,100.0,0.5
13459,2014-11-26,41.080206,NaN,NaN,NaN,51.930,28.78,37.611040,33.375548,43.406102,...,35.85,NaN,NaN,NaN,1.3800,NaN,NaN,NaN,100.0,0.5
13460,2014-11-28,41.080206,NaN,NaN,NaN,51.740,28.86,37.611040,33.375548,46.842298,...,35.77,NaN,NaN,NaN,1.4200,NaN,NaN,NaN,100.0,0.5
13461,2014-12-01,39.974866,NaN,NaN,NaN,50.100,29.59,36.823039,33.800525,46.214903,...,35.27,NaN,NaN,NaN,1.4000,NaN,NaN,NaN,100.0,0.5
13462,2014-12-02,40.349721,NaN,NaN,NaN,50.670,31.61,37.459946,33.769888,46.195598,...,35.25,NaN,NaN,NaN,1.3700,NaN,NaN,NaN,100.0,0.5
13463,2014-12-03,40.590012,NaN,NaN,NaN,50.280,31.11,37.459946,33.769888,46.562383,...,35.71,NaN,NaN,NaN,1.4000,NaN,NaN,NaN,100.0,0.5
13464,2014-12-04,40.628459,NaN,NaN,NaN,50.410,30.46,37.396647,33.816833,47.923348,...,35.47,NaN,NaN,NaN,1.3900,NaN,NaN,NaN,100.0,0.5
13465,2014-12-05,40.657294,NaN,NaN,NaN,50.990,31.71,37.499140,33.800525,49.236052,...,34.47,NaN,NaN,NaN,1.3803,NaN,NaN,NaN,100.0,0.5
13466,2014-12-08,39.897973,NaN,NaN,NaN,49.620,31.00,37.283572,33.800525,49.052660,...,34.63,NaN,NaN,NaN,1.2200,NaN,NaN,NaN,100.0,0.5
13467,2014-12-09,39.792245,NaN,NaN,NaN,50.510,32.41,37.283572,33.148235,46.629949,...,34.45,NaN,NaN,NaN,1.2100,NaN,NaN,NaN,100.0,0.5
13468,2014-12-10,38.773410,NaN,NaN,NaN,49.205,29.59,36.254722,33.148235,47.238040,...,34.22,NaN,NaN,NaN,1.1800,NaN,NaN,NaN,100.0,0.5
13469,2014-12-11,39.042536,NaN,NaN,NaN,49.940,29.78,36.320568,33.148235,48.772745,...,34.56,NaN,NaN,NaN,1.1100,NaN,NaN,NaN,100.0,0.5
13470,2014-12-12,38.177487,NaN,NaN,NaN,50.240,29.96,35.480732,33.148235,48.232220,...,36.71,NaN,NaN,NaN,1.0900,NaN,NaN,NaN,100.0,0.5
13471,2014-12-15,37.177875,NaN,NaN,NaN,49.820,29.70,35.480732,32.515710,49.071964,...,36.66,NaN,NaN,NaN,1.1200,NaN,NaN,NaN,100.0,0.5
13472,2014-12-16,36.976030,NaN,NaN,NaN,48.850,29.40,35.519829,31.814003,46.292121,...,35.89,NaN,NaN,NaN,1.1200,NaN,NaN,NaN,100.0,0.5
13473,2014-12-17,38.215934,NaN,NaN,NaN,50.120,29.75,35.892174,32.196019,47.102908,...,37.45,NaN,NaN,NaN,1.1200,NaN,NaN,NaN,100.0,0.5
13474,2014-12-18,39.119429,NaN,NaN,NaN,50.910,29.79,36.499686,32.465650,48.396308,...,37.93,NaN,NaN,NaN,1.0700,NaN,NaN,NaN,100.0,0.5
13475,2014-12-19,39.773021,NaN,NaN,NaN,50.880,29.50,36.813142,32.895163,48.946485,...,37.31,NaN,NaN,NaN,1.0800,NaN,NaN,NaN,100.0,0.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14416,2018-09-17,68.935860,42.83,NaN,12.0070,65.900,7.34,50.749334,NaN,40.320000,...,28.10,24.11,NaN,NaN,NaN,8.00,14.35,6.650,NaN,NaN
14417,2018-09-18,68.786173,43.12,NaN,11.9800,64.980,7.24,50.919332,NaN,40.790000,...,27.85,23.31,NaN,NaN,NaN,8.00,14.48,7.290,NaN,NaN
14418,2018-09-19,69.414858,42.63,NaN,12.0300,67.090,6.75,51.429325,NaN,41.600000,...,27.65,22.91,NaN,NaN,NaN,8.00,15.33,7.860,NaN,NaN
14419,2018-09-20,70.981582,42.93,NaN,12.0600,68.350,7.16,52.149315,NaN,41.890000,...,28.60,22.99,NaN,NaN,NaN,8.00,16.61,8.010,NaN,NaN
14420,2018-09-21,70.572438,43.79,NaN,11.9885,67.930,7.40,52.359313,NaN,43.600000,...,28.10,23.36,NaN,NaN,NaN,8.00,16.55,8.470,NaN,NaN
14421,2018-09-24,69.804044,41.96,NaN,12.0000,67.590,7.25,52.359313,NaN,41.980000,...,27.60,22.93,NaN,NaN,NaN,8.00,15.67,8.260,NaN,NaN
14422,2018-09-25,70.233147,41.24,NaN,12.0065,67.860,7.27,53.329300,NaN,40.810000,...,27.00,22.26,NaN,NaN,NaN,8.00,16.04,8.330,NaN,NaN
14423,2018-09-26,70.183251,40.48,NaN,11.9500,68.130,7.20,53.330000,NaN,41.040000,...,27.05,22.43,NaN,NaN,NaN,8.00,16.04,8.260,NaN,NaN
14424,2018-09-27,70.652271,40.50,NaN,11.8393,68.480,7.28,53.650000,NaN,41.500000,...,26.55,22.89,NaN,NaN,NaN,8.00,15.79,7.840,NaN,NaN
14425,2018-09-28,70.392813,40.40,NaN,11.9200,68.120,7.63,53.770000,NaN,41.330000,...,26.35,23.11,NaN,NaN,NaN,8.00,15.70,8.160,NaN,NaN
14426,2018-10-01,71.260000,40.86,NaN,11.8899,67.240,7.42,53.700000,NaN,39.610000,...,26.83,21.47,NaN,NaN,NaN,8.00,15.44,7.860,NaN,NaN
14427,2018-10-02,71.680000,41.56,NaN,12.0300,66.630,6.90,53.000000,NaN,38.500000,...,25.10,21.11,NaN,NaN,NaN,8.00,14.97,7.810,NaN,NaN
14428,2018-10-03,72.120000,42.89,NaN,11.9799,67.250,7.32,53.380000,NaN,38.800000,...,25.43,21.10,NaN,NaN,NaN,8.00,14.95,7.910,NaN,NaN
14429,2018-10-04,70.660000,43.11,NaN,11.9800,65.260,7.06,51.750000,NaN,37.920000,...,25.40,21.32,NaN,NaN,NaN,8.00,14.34,7.535,NaN,NaN
14430,2018-10-05,70.300000,42.06,NaN,12.0100,64.580,7.00,51.200000,NaN,36.440000,...,24.90,21.16,NaN,NaN,NaN,8.00,13.81,7.700,NaN,NaN
14431,2018-10-08,69.500000,38.74,NaN,11.8601,63.090,7.08,50.240000,NaN,35.900000,...,24.47,19.94,NaN,NaN,NaN,8.00,13.27,7.350,NaN,NaN
14432,2018-10-09,69.410000,37.64,NaN,11.8700,61.520,7.11,50.240000,NaN,33.550000,...,24.75,19.65,NaN,NaN,NaN,8.00,13.68,7.590,NaN,NaN
14433,2018-10-10,66.670000,36.06,NaN,11.9300,58.410,7.00,48.250000,NaN,31.610000,...,23.87,18.51,NaN,NaN,NaN,8.00,13.00,7.000,NaN,NaN
14434,2018-10-11,64.890000,35.67,NaN,12.2300,59.930,6.90,47.860000,NaN,31.270000,...,22.31,17.83,NaN,NaN,NaN,8.00,12.58,7.140,NaN,NaN
14435,2018-10-12,66.240000,35.67,NaN,12.2000,61.980,6.92,48.710000,NaN,30.910000,...,22.78,18.10,NaN,NaN,NaN,8.00,13.24,7.250,NaN,NaN
14436,2018-10-15,65.630000,35.34,NaN,12.2700,60.930,7.01,48.680000,NaN,31.780000,...,23.12,19.79,NaN,NaN,NaN,8.00,13.42,7.190,NaN,NaN
14437,2018-10-16,67.460000,36.19,NaN,12.2400,62.830,6.89,50.330000,NaN,33.280000,...,22.94,20.91,NaN,NaN,NaN,8.00,13.84,7.570,NaN,NaN
14438,2018-10-17,67.200000,36.70,NaN,12.2200,62.190,6.87,49.911800,NaN,33.570000,...,22.60,20.83,NaN,NaN,NaN,8.00,13.49,7.430,NaN,NaN
14439,2018-10-18,65.750000,38.85,NaN,12.2600,60.060,6.90,49.120000,NaN,32.060000,...,22.06,20.90,NaN,NaN,NaN,8.00,13.22,7.290,NaN,NaN
14440,2018-10-19,64.470000,38.60,NaN,12.2600,60.390,6.92,48.890000,NaN,32.040000,...,21.35,20.00,NaN,NaN,NaN,8.00,12.75,6.790,NaN,NaN
14441,2018-10-22,64.280000,39.46,NaN,12.2216,62.200,7.09,48.760000,NaN,32.160000,...,21.73,19.40,NaN,NaN,NaN,8.00,12.55,6.270,NaN,NaN
14442,2018-10-23,62.730000,37.32,NaN,12.3000,61.350,6.84,47.720000,NaN,32.380000,...,21.71,19.49,NaN,NaN,NaN,8.00,12.85,6.170,NaN,NaN
14443,2018-10-24,61.130000,34.20,NaN,12.3000,59.070,6.84,45.840000,NaN,30.340000,...,21.92,17.91,NaN,NaN,NaN,8.00,12.54,5.750,NaN,NaN
14444,2018-10-25,62.610000,34.56,NaN,12.2901,60.740,6.84,46.400000,NaN,32.370000,...,23.40,19.32,NaN,NaN,NaN,8.00,12.63,5.990,NaN,NaN
14445,2018-10-26,62.730000,34.25,NaN,12.3476,60.170,6.66,45.800000,NaN,32.460000,...,23.66,19.03,NaN,NaN,NaN,8.04,13.02,6.100,NaN,NaN

In [17]:
pivot_df.to_csv("stocks_clean.csv", index=False)

In [7]:
df.describe

<bound method NDFrame.describe of             A  1999-11-18   45.5   50.0   40.0   44.0  44739900.0  0.0  1.0  \
0           A  1999-11-19  42.94  43.00  39.81  40.38  10897100.0  0.0  1.0
1           A  1999-11-22  41.31  44.00  40.06  44.00   4705200.0  0.0  1.0
2           A  1999-11-23  42.50  43.63  40.25  40.25   4274400.0  0.0  1.0
3           A  1999-11-24  40.13  41.94  40.00  41.06   3464400.0  0.0  1.0
4           A  1999-11-26  40.88  41.50  40.75  41.19   1237100.0  0.0  1.0
5           A  1999-11-29  41.00  42.44  40.56  42.13   2914700.0  0.0  1.0
6           A  1999-11-30  42.00  42.94  40.94  42.19   3083000.0  0.0  1.0
7           A  1999-12-01  42.19  43.44  41.88  42.94   2115400.0  0.0  1.0
8           A  1999-12-02  43.75  45.00  43.19  44.13   2195900.0  0.0  1.0
9           A  1999-12-03  44.94  45.69  44.31  44.50   2175700.0  0.0  1.0
10          A  1999-12-06  45.25  46.44  45.19  45.75   1610000.0  0.0  1.0
11          A  1999-12-07  45.75  46.00  44.31  45.25   1585100.0  0.0  1.0
12          A  1999-12-08  45.25  45.63  44.81  45.19   1350400.0  0.0  1.0
13          A  1999-12-09  45.25  45.94  45.25  45.81   1451400.0  0.0  1.0
14          A  1999-12-10  45.69  45.94  44.75  44.75   1190800.0  0.0  1.0
15          A  1999-12-13  45.50  46.25  44.38  45.50   2875900.0  0.0  1.0
16          A  1999-12-14  45.38  45.38  42.06  43.00   1665900.0  0.0  1.0
17          A  1999-12-15  42.00  42.31  41.00  41.69   2087100.0  0.0  1.0
18          A  1999-12-16  42.00  48.00  42.00  47.25   1848300.0  0.0  1.0
19          A  1999-12-17  46.38  47.12  45.44  45.94   2652400.0  0.0  1.0
20          A  1999-12-20  46.25  46.94  46.13  46.88    856100.0  0.0  1.0
21          A  1999-12-21  46.69  46.69  46.00  46.63   1616200.0  0.0  1.0
22          A  1999-12-22  46.63  47.56  46.31  47.56   1363200.0  0.0  1.0
23          A  1999-12-23  47.50  50.00  47.44  49.75   1544700.0  0.0  1.0
24          A  1999-12-27  49.94  53.19  49.56  52.81   1451800.0  0.0  1.0
25          A  1999-12-28  54.25  61.50  53.94  61.50   2546500.0  0.0  1.0
26          A  1999-12-29  63.00  79.06  62.94  72.00   7524000.0  0.0  1.0
27          A  1999-12-30  76.00  80.00  74.25  79.25   4771900.0  0.0  1.0
28          A  1999-12-31  79.50  79.94  76.25  77.31   1381400.0  0.0  1.0
29          A  2000-01-03  78.75  78.94  67.38  72.00   3343600.0  0.0  1.0
...       ...         ...    ...    ...    ...    ...         ...  ...  ...
31846220  ZZZ  2017-07-25   0.01   0.01   0.01   0.01         0.0  0.0  1.0
31846221  ZZZ  2017-07-26   0.01   0.01   0.01   0.01         0.0  0.0  1.0
31846222  ZZZ  2017-07-27   0.01   0.01   0.01   0.01         0.0  0.0  1.0
31846223  ZZZ  2017-07-28   0.01   0.01   0.01   0.01         0.0  0.0  1.0
31846224  ZZZ  2017-07-31   0.01   0.01   0.01   0.01         0.0  0.0  1.0
31846225  ZZZ  2017-08-01   0.01   0.01   0.01   0.01         0.0  0.0  1.0
31846226  ZZZ  2017-08-02   0.01   0.01   0.01   0.01         0.0  0.0  1.0
31846227  ZZZ  2017-08-03   0.01   0.01   0.01   0.01         0.0  0.0  1.0
31846228  ZZZ  2017-08-04   0.01   0.01   0.01   0.01         0.0  0.0  1.0
31846229  ZZZ  2017-08-07   0.01   0.01   0.01   0.01         0.0  0.0  1.0
31846230  ZZZ  2017-08-08   0.01   0.01   0.01   0.01         0.0  0.0  1.0
31846231  ZZZ  2017-08-09   0.01   0.01   0.01   0.01         0.0  0.0  1.0
31846232  ZZZ  2017-08-10   0.01   0.01   0.01   0.01         0.0  0.0  1.0
31846233  ZZZ  2017-08-11   0.01   0.01   0.01   0.01         0.0  0.0  1.0
31846234  ZZZ  2017-08-14   0.01   0.01   0.01   0.01         0.0  0.0  1.0
31846235  ZZZ  2017-08-15   0.01   0.01   0.01   0.01         0.0  0.0  1.0
31846236  ZZZ  2017-08-16   0.01   0.01   0.01   0.01         0.0  0.0  1.0
31846237  ZZZ  2017-08-17   0.01   0.01   0.01   0.01         0.0  0.0  1.0
31846238  ZZZ  2017-08-18   0.01   0.01   0.01   0.01         0.0  0.0  1.0
31846239  ZZZ  2017-08-21   0.01   0.01   0.01   0.01         0.0  0.0  1.0
31846240  ZZZ  2017-08-22   0.01   0.01   0.01   0.01         0.0  0.0  1.0
31846241  ZZZ  2017-08-23   0.01   0.01   0.01   0.01         0.0  0.0  1.0
31846242  ZZZ  2017-08-24   0.01   0.01   0.01   0.01         0.0  0.0  1.0
31846243  ZZZ  2017-08-25   0.01   0.01   0.01   0.01         0.0  0.0  1.0
31846244  ZZZ  2017-08-28   0.01   0.01   0.01   0.01         0.0  0.0  1.0
31846245  ZZZ  2017-08-29   0.01   0.01   0.01   0.01         0.0  0.0  1.0
31846246  ZZZ  2017-08-30   0.01   0.01   0.01   0.01         0.0  0.0  1.0
31846247  ZZZ  2017-08-31   0.01   0.01   0.01   0.01         0.0  0.0  1.0
31846248  ZZZ  2017-09-01   0.01   0.01   0.01   0.01         0.0  0.0  1.0
31846249  ZZZ  2017-09-05   0.01   0.01   0.01   0.01       100.0  0.0  1.0

          30.76253232829783  33.80498058054707  27.043984464437653  \
0                 29.031717          29.072283           26.915526
1                 27.929675          29.748383           27.084550
2                 28.734233          29.498226           27.213009
3                 27.131877          28.355618           27.043984
4                 27.638952          28.058134           27.551059
5                 27.720084          28.693668           27.422600
6                 28.396184          29.031717           27.679518
7                 28.524643          29.369767           28.315052
8                 29.579358          30.424483           29.200742
9                 30.383917          30.890991           29.957974
10                30.593507          31.398066           30.552941
11                30.931557          31.100582           29.957974
12                30.593507          30.850425           30.296024
13                30.593507          31.060016           30.593507
14                30.890991          31.060016           30.255458
15                30.762532          31.269607           30.005301
16                30.681400          30.681400           28.436750
17                28.396184          28.605775           27.720084
18                28.396184          32.452781           28.396184
19                31.357500          31.857814           30.721966
20                31.269607          31.736116           31.188475
21                31.567091          31.567091           31.100582
22                31.526525          32.155298           31.310173
23                32.114732          33.804981           32.074166
24                33.764415          35.961738           33.507497
25                36.678404          41.580126           36.468813
26                42.594276          53.452435           42.553710
27                51.383570          54.087969           50.200396
28                53.749919          54.047403           51.552595
29                53.242844          53.371303           45.555592
...                     ...                ...                 ...
31846220           0.010000           0.010000            0.010000
31846221           0.010000           0.010000            0.010000
31846222           0.010000           0.010000            0.010000
31846223           0.010000           0.010000            0.010000
31846224           0.010000           0.010000            0.010000
31846225           0.010000           0.010000            0.010000
31846226           0.010000           0.010000            0.010000
31846227           0.010000           0.010000            0.010000
31846228           0.010000           0.010000            0.010000
31846229           0.010000           0.010000            0.010000
31846230           0.010000           0.010000            0.010000
31846231           0.010000           0.010000            0.010000
31846232           0.010000           0.010000            0.010000
31846233           0.010000           0.010000            0.010000
31846234           0.010000           0.010000            0.010000
31846235           0.010000           0.010000            0.010000
31846236           0.010000           0.010000            0.010000
31846237           0.010000           0.010000            0.010000
31846238           0.010000           0.010000            0.010000
31846239           0.010000           0.010000            0.010000
31846240           0.010000           0.010000            0.010000
31846241           0.010000           0.010000            0.010000
31846242           0.010000           0.010000            0.010000
31846243           0.010000           0.010000            0.010000
31846244           0.010000           0.010000            0.010000
31846245           0.010000           0.010000            0.010000
31846246           0.010000           0.010000            0.010000
31846247           0.010000           0.010000            0.010000
31846248           0.010000           0.010000            0.010000
31846249           0.010000           0.010000            0.010000

          29.748382910881418  44739900.0.1
0                  27.300902    10897100.0
1                  29.748383     4705200.0
2                  27.213009     4274400.0
3                  27.760650     3464400.0
4                  27.848543     1237100.0
5                  28.484077     2914700.0
6                  28.524643     3083000.0
7                  29.031717     2115400.0
8                  29.836276     2195900.0
9                  30.086433     2175700.0
10                 30.931557     1610000.0
11                 30.593507     1585100.0
12                 30.552941     1350400.0
13                 30.972123     1451400.0
14                 30.255458     1190800.0
15                 30.762532     2875900.0
16                 29.072283     1665900.0
17                 28.186593     2087100.0
18                 31.945707     1848300.0
19                 31.060016     2652400.0
20                 31.695550      856100.0
21                 31.526525     1616200.0
22                 32.155298     1363200.0
23                 33.635956     1544700.0
24                 35.704820     1451800.0
25                 41.580126     2546500.0
26                 48.679172     7524000.0
27                 53.580894     4771900.0
28                 52.269261     1381400.0
29                 48.679172     3343600.0
...                      ...           ...
31846220            0.010000           0.0
31846221            0.010000           0.0
31846222            0.010000           0.0
31846223            0.010000           0.0
31846224            0.010000           0.0
31846225            0.010000           0.0
31846226            0.010000           0.0
31846227            0.010000           0.0
31846228            0.010000           0.0
31846229            0.010000           0.0
31846230            0.010000           0.0
31846231            0.010000           0.0
31846232            0.010000           0.0
31846233            0.010000           0.0
31846234            0.010000           0.0
31846235            0.010000           0.0
31846236            0.010000           0.0
31846237            0.010000           0.0
31846238            0.010000           0.0
31846239            0.010000           0.0
31846240            0.010000           0.0
31846241            0.010000           0.0
31846242            0.010000           0.0
31846243            0.010000           0.0
31846244            0.010000           0.0
31846245            0.010000           0.0
31846246            0.010000           0.0
31846247            0.010000           0.0
31846248            0.010000           0.0
31846249            0.010000         100.0

[31846250 rows x 14 columns]>